const TodoActionTypes = {
	ADD_TODO: 'ADD_TODO',
	DELETE_TODO: 'DELETE_TODO',
	TOGGLE_TODO: 'TOGGLE_TODO',
	TODO_UPDATE_DATABASE:'TODO_UPDATE_DATA',
	TODO_FETCH_DATABASE:'TODO_FETCH_DATABASE'
  };

  export default TodoActionTypes;